#!/bin/sh
lb config noauto \
     --clean \
     --mode debian \
     --architectures amd64 \
     --linux-flavours amd64 \
     --bootappend-live "auto=true priority=critical vga=normal locales=en_US.UTF-8 keyboard-layouts=us" \
     --bootappend-install "auto=true priority=critical locales=en_US.UTF-8 keyboard-layouts=us" \
     --distribution jessie \
     --debian-installer live \
     --debian-installer-gui false \
     --binary-images iso \
     --initsystem systemd \
     --parent-mirror-bootstrap http://httpredir.debian.org/debian \
     --parent-mirror-binary http://httpredir.debian.org/debian \
     --mirror-bootstrap http://httpredir.debian.org/debian \
     --mirror-binary http://httpredir.debian.org/debian \
     "${@}"
