#!/bin/sh
lb config noauto \
     --clean \
     --quiet \
     --mode debian \
     --linux-flavours amd64 \
     --bootappend-live "auto=true priority=critical vga=normal locales=en_US.UTF-8 keyboard-layouts=us" \
     --bootappend-install "auto=true priority=critical locales=en_US.UTF-8 keyboard-layouts=us" \
     --distribution jessie \
     --debian-installer live \
     --debian-installer-gui false \
     --binary-images iso \
     --mirror-bootstrap http://ftp.us.debian.org/debian/ \
     --mirror-binary http://ftp.us.debian.org/debian/ \
     "${@}"
